#!/usr/bin/tclsh
#                          this is a -*-Tcl-*- file
package require tdom
package require Tk

# gives us [table]
source treemaker.tcl

set NS {
    ts http://tokenscript.org/2020/06/tokenscript
    asnx urn:ietf:params:xml:ns:asnx
    ethereum urn:ethereum:constantinople
}

# XPaths (tcl variables allowed in it, read domNode(3tcl)
set xp-attributes {
    {label	Label	string(ts:label/ts:string/text())}
    {syntax	Syntax	string(ts:type/ts:syntax/text())}
    {origins	Origins	name(ts:origins/*)}
}

set xp-cards {
    {type	Type	@type}
    {view-lang	View-Languages ts:view/@xml:lang}
}

set xp-dataObjects {
    {elements	Elements string(//element/@name)}
    {references	References count(ancestor-or-self::node()[last()]//ethereum:event[@module=$name])}
}

if { $argc != 1 } {
    puts "Requires one argument: the filename of a tokenscript."
    puts "For example, try $argv0 ../../TokenScript-Examples/examples/UEFA/UEFA.xml"
    puts "Please try again."
    exit 255
} else {
    set data [open [lindex $argv 0] r]
}

pack [ttk::notebook .nb]
.nb add [frame .nb.f1] -text "Token Attributes"
.nb add [frame .nb.f2] -text "Cards"
.nb add [frame .nb.f3] -text "Data Objects"
.nb add [frame .nb.f4] -text "Selections"
.nb add [frame .nb.f5] -text "Translations"

set doc [dom parse [read $data]]
$doc selectNodesNamespaces $NS
set root [$doc documentElement]

set nodes [$root selectNodes {//ts:attribute}]
puts [table .nb.f1.table $nodes {*}${xp-attributes}]

set nodes [$root selectNodes {/ts:token/ts:cards/ts:card}]
puts [table .nb.f2.table $nodes {*}${xp-cards}]

set nodes [$root selectNodes {//asnx:module}]
puts [table .nb.f3.table $nodes {*}${xp-dataObjects}]

pack .nb.f1.table
pack .nb.f2.table
pack .nb.f3.table

$doc delete
