#!/usr/bin/tclsh
#                          this is a -*-Tcl-*- file
package require tdom
package require Tk

# gives us [table]
source treemaker.tcl

set NS {
    ts http://tokenscript.org/2020/06/tokenscript
    asnx urn:ietf:params:xml:ns:asnx
    ethereum urn:ethereum:constantinople
}

# XPaths (tcl variables allowed in it, read domNode(3tcl)
set xp-attributes {
    {label	Label	string(ts:label/ts:string/text())}
    {syntax	Syntax	string(ts:type/ts:syntax/text())}
    {origins	Origins	name(ts:origins/*)}
}

set xp-cards {
    {type	Type	@type}
    {view-lang	View-Languages ts:view/@xml:lang}
}

set xp-dataObjects {
    {elements	Elements //element/@name}
    {references	References count(//ethereum:event[@module=$name])}
}

set xp-localisation {
    {parent	Of	name(..)}
    {name	Name	../@name}
    {l10n	Localistaion string(.//ts:string)}
}

if { $argc != 1 } {
    puts "Requires one argument: the filename of a tokenscript."
    puts "For example, try $argv0 examples/ENS/ENS.xml"
    puts "Please try again."
    exit 255
} else {
    set data [open [lindex $argv 0] r]
}

pack [ttk::notebook .nb]
.nb add [frame .nb.f1] -text "Token Attributes"
.nb add [frame .nb.f2] -text "Cards"
.nb add [frame .nb.f3] -text "Data Objects"
.nb add [frame .nb.f4] -text "Strings"

set doc [dom parse [read $data]]
$doc selectNodesNamespaces $NS
set root [$doc documentElement]

set nodes [$root selectNodes {//ts:attribute}]
set rows [table .nb.f1.table $nodes {*}${xp-attributes}]
.nb tab .nb.f1 -text "Token Attributes ([llength $rows])"

set nodes [$root selectNodes {/ts:token/ts:cards/ts:card}]
set rows [table .nb.f2.table $nodes {*}${xp-cards}]
.nb tab .nb.f2 -text "Cards ([llength $rows])"

set nodes [$root selectNodes {//asnx:module}]
set rows [table .nb.f3.table $nodes {*}${xp-dataObjects}]
.nb tab .nb.f3 -text "Data Objects ([llength $rows])"

set nodes [$root selectNodes {//ts:label}]
set rows [table .nb.f4.table $nodes {*}${xp-localisation}]
.nb tab .nb.f4 -text "Strings ([llength $rows])"

pack .nb.f1.table
pack .nb.f2.table
pack .nb.f3.table
pack .nb.f4.table

$doc delete
